version: "3.7"
services:
  db:
      image: mariadb
      container_name: loady_database
      environment:
          - MYSQL_ROOT_PASSWORD=Loady135
          - MYSQL_DATABASE=Loady
      ports:
        - 3306:3306
      volumes:
          - ./database:/var/lib/mysql
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: loady_phpmyadmin
      environment:
          - PMA_HOST=db
      restart: always
      ports:
          - 4040:80
      volumes:
          - /sessions
      links:
          - db